project_id = "pjowmwyaribfewhbaazl"

[functions.check-email]
verify_jwt = false

[functions.create-client]
verify_jwt = false

[functions.delete-client]
verify_jwt = false

[functions.create-impersonation]
verify_jwt = false

[functions.validate-impersonation]
verify_jwt = false

[functions.end-impersonation]
verify_jwt = false

[functions.invite-staff]
verify_jwt = false

[functions.remove-staff]
verify_jwt = false

[functions.reset-staff-password]
verify_jwt = false

[functions.send-smtp-email]
verify_jwt = false

[functions.seed-global-medicines]
verify_jwt = false

[functions.import-medex-manufacturers]
verify_jwt = false

[functions.import-medex-medicines]
verify_jwt = false
