import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// MedEx-style comprehensive medicine database with all clinical fields
const MEDICINES_DATA = [
  // ========== ANALGESICS / ANTIPYRETICS ==========
  {
    name: 'Napa 500',
    generic_name: 'Paracetamol',
    dosage_form: 'Tablet',
    strength: '500mg',
    manufacturer_name: 'Beximco Pharmaceuticals Ltd.',
    unit_price: 2.50,
    strip_price: 25.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Analgesic & Antipyretic',
    therapeutic_class: 'Non-Opioid Analgesics',
    indication: 'Fever, mild to moderate pain including headache, toothache, backache, migraine, neuralgia, muscle aches, period pain, post-operative pain.',
    pharmacology: 'Paracetamol is a para-aminophenol derivative that exhibits analgesic and antipyretic activity. It does not possess anti-inflammatory activity. The mechanism of action is not fully understood but may involve inhibition of prostaglandin synthesis in the CNS.',
    mode_of_action: 'Inhibits prostaglandin synthesis centrally by blocking COX enzymes, reducing fever via action on the hypothalamic heat-regulating center.',
    dosage_adult: '500mg-1g every 4-6 hours as needed. Maximum 4g daily.',
    dosage_pediatric: '10-15 mg/kg every 4-6 hours. Maximum 5 doses in 24 hours.',
    administration: 'Oral administration. Can be taken with or without food.',
    contraindications: 'Hypersensitivity to paracetamol. Severe hepatic impairment.',
    side_effects: 'Rare: Skin rashes, blood dyscrasias (thrombocytopenia, agranulocytosis). Hepatotoxicity with overdose.',
    precautions: 'Use with caution in hepatic impairment, chronic alcohol use, dehydration, and chronic malnutrition.',
    drug_interactions: 'Warfarin: May enhance anticoagulant effect. Metoclopramide: Increases absorption rate. Cholestyramine: Reduces absorption.',
    overdose_info: 'Overdose can cause severe hepatotoxicity. Symptoms include nausea, vomiting, abdominal pain. N-acetylcysteine is the specific antidote.',
    pregnancy_category: 'B',
    lactation_info: 'Compatible with breastfeeding. Excreted in breast milk in small amounts.',
    storage: 'Store below 30°C. Protect from light and moisture.',
  },
  {
    name: 'Ace 500',
    generic_name: 'Paracetamol',
    dosage_form: 'Tablet',
    strength: '500mg',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 2.00,
    strip_price: 20.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Analgesic & Antipyretic',
    therapeutic_class: 'Non-Opioid Analgesics',
    indication: 'Fever, mild to moderate pain including headache, toothache, backache, migraine, neuralgia, muscle aches.',
    pharmacology: 'Paracetamol is a para-aminophenol derivative that exhibits analgesic and antipyretic activity without significant anti-inflammatory action.',
    mode_of_action: 'Acts primarily in the CNS, inhibiting prostaglandin synthesis and blocking pain impulse generation peripherally.',
    dosage_adult: '500mg-1g every 4-6 hours as needed. Maximum 4g daily.',
    dosage_pediatric: '10-15 mg/kg every 4-6 hours. Maximum 5 doses in 24 hours.',
    administration: 'Oral. May be taken with or without food.',
    contraindications: 'Hypersensitivity to paracetamol. Severe hepatic impairment.',
    side_effects: 'Rare: Allergic skin reactions, blood disorders.',
    precautions: 'Hepatic impairment, chronic alcoholism, dehydration.',
    drug_interactions: 'Warfarin, Metoclopramide, Cholestyramine.',
    overdose_info: 'Hepatotoxicity with overdose. N-acetylcysteine is the antidote.',
    pregnancy_category: 'B',
    lactation_info: 'Safe during breastfeeding.',
    storage: 'Store below 30°C.',
  },
  {
    name: 'Napa Extra',
    generic_name: 'Paracetamol + Caffeine',
    dosage_form: 'Tablet',
    strength: '500mg + 65mg',
    manufacturer_name: 'Beximco Pharmaceuticals Ltd.',
    unit_price: 5.00,
    strip_price: 50.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Analgesic & Antipyretic',
    therapeutic_class: 'Combination Analgesics',
    indication: 'Migraine, tension headache, dental pain, muscular pain, menstrual pain.',
    pharmacology: 'Paracetamol provides analgesic and antipyretic effects. Caffeine acts as an adjuvant analgesic, enhancing paracetamol absorption and efficacy.',
    mode_of_action: 'Paracetamol inhibits central COX. Caffeine blocks adenosine receptors and enhances analgesic effect.',
    dosage_adult: '1-2 tablets every 4-6 hours. Maximum 8 tablets daily.',
    dosage_pediatric: 'Not recommended for children under 12 years.',
    administration: 'Oral. Take with water.',
    contraindications: 'Hypersensitivity. Severe hepatic impairment. Caffeine-sensitive patients.',
    side_effects: 'Nervousness, insomnia, GI disturbances with caffeine. Hepatotoxicity with overdose.',
    precautions: 'Avoid in patients with anxiety disorders, insomnia, cardiac arrhythmias.',
    drug_interactions: 'CNS stimulants, MAO inhibitors, anticoagulants.',
    overdose_info: 'Combined toxicity risk. Treat as paracetamol overdose with N-acetylcysteine.',
    pregnancy_category: 'C',
    lactation_info: 'Caffeine excreted in breast milk. Use with caution.',
    storage: 'Store below 30°C. Protect from moisture.',
  },

  // ========== PPIs / GASTRIC ==========
  {
    name: 'Seclo 20',
    generic_name: 'Omeprazole',
    dosage_form: 'Capsule',
    strength: '20mg',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 6.00,
    strip_price: 60.00,
    pack_size: '10 capsules/strip',
    drug_class: 'Proton Pump Inhibitor',
    therapeutic_class: 'Anti-Ulcerant Drugs',
    indication: 'Gastric ulcer, duodenal ulcer, GERD, Zollinger-Ellison syndrome, H. pylori eradication (with antibiotics), NSAID-associated gastric ulcer.',
    pharmacology: 'Omeprazole is a substituted benzimidazole that suppresses gastric acid secretion by specific inhibition of the H+/K+ ATPase enzyme system at the secretory surface of the gastric parietal cell.',
    mode_of_action: 'Irreversibly inhibits the proton pump (H+/K+ ATPase) in parietal cells, blocking the final step of acid production.',
    dosage_adult: '20-40mg once daily for 4-8 weeks. Maintenance: 10-20mg daily.',
    dosage_pediatric: '0.7-3.3 mg/kg/day for children over 1 year.',
    administration: 'Take before meals, preferably in the morning. Swallow capsule whole, do not crush or chew.',
    contraindications: 'Hypersensitivity to omeprazole or other proton pump inhibitors.',
    side_effects: 'Common: Headache, diarrhea, nausea, abdominal pain. Rare: Vitamin B12 deficiency, hypomagnesemia with prolonged use.',
    precautions: 'Long-term use may increase risk of bone fractures, Clostridium difficile infection, and vitamin B12 deficiency.',
    drug_interactions: 'Clopidogrel: Reduced antiplatelet effect. Methotrexate: Increased methotrexate levels. Ketoconazole: Decreased absorption.',
    overdose_info: 'Symptoms are transient. Treatment is supportive and symptomatic.',
    pregnancy_category: 'C',
    lactation_info: 'Not recommended during breastfeeding as omeprazole is excreted in breast milk.',
    storage: 'Store below 25°C in a dry place. Protect from light.',
  },
  {
    name: 'Losectil 20',
    generic_name: 'Esomeprazole',
    dosage_form: 'Capsule',
    strength: '20mg',
    manufacturer_name: 'Eskayef Pharmaceuticals Ltd.',
    unit_price: 8.00,
    strip_price: 80.00,
    pack_size: '10 capsules/strip',
    drug_class: 'Proton Pump Inhibitor',
    therapeutic_class: 'Anti-Ulcerant Drugs',
    indication: 'GERD, erosive esophagitis, peptic ulcer, H. pylori eradication, Zollinger-Ellison syndrome.',
    pharmacology: 'Esomeprazole is the S-isomer of omeprazole. It suppresses gastric acid secretion by specifically inhibiting the H+/K+-ATPase in gastric parietal cells.',
    mode_of_action: 'Specifically inhibits the proton pump in parietal cells, providing potent and sustained acid suppression.',
    dosage_adult: '20-40mg once daily.',
    dosage_pediatric: '10-20mg once daily for children 1-11 years weighing ≥20kg.',
    administration: 'Take at least 1 hour before meals. Swallow whole.',
    contraindications: 'Hypersensitivity to esomeprazole or substituted benzimidazoles.',
    side_effects: 'Headache, diarrhea, nausea, flatulence, abdominal pain.',
    precautions: 'Long-term use: Risk of bone fractures, hypomagnesemia, vitamin B12 deficiency.',
    drug_interactions: 'Clopidogrel, methotrexate, ketoconazole, HIV protease inhibitors.',
    overdose_info: 'Symptoms are transient. Provide supportive care.',
    pregnancy_category: 'C',
    lactation_info: 'Caution advised. Present in breast milk.',
    storage: 'Store below 25°C.',
  },
  {
    name: 'Pantonix 40',
    generic_name: 'Pantoprazole',
    dosage_form: 'Tablet',
    strength: '40mg',
    manufacturer_name: 'Opsonin Pharma Limited',
    unit_price: 7.00,
    strip_price: 70.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Proton Pump Inhibitor',
    therapeutic_class: 'Anti-Ulcerant Drugs',
    indication: 'GERD, peptic ulcer, Zollinger-Ellison syndrome, stress ulcer prophylaxis.',
    pharmacology: 'Pantoprazole is a proton pump inhibitor that suppresses the final step in gastric acid production by forming a covalent bond with the H+/K+ ATPase enzyme.',
    mode_of_action: 'Irreversibly inhibits the gastric proton pump in parietal cells.',
    dosage_adult: '40mg once daily for 4-8 weeks.',
    dosage_pediatric: 'Not established for children under 5 years.',
    administration: 'Take before breakfast. Swallow whole, do not crush.',
    contraindications: 'Hypersensitivity to pantoprazole or substituted benzimidazoles.',
    side_effects: 'Headache, diarrhea, nausea, abdominal pain, flatulence.',
    precautions: 'Long-term use may cause hypomagnesemia, vitamin B12 deficiency, increased fracture risk.',
    drug_interactions: 'Atazanavir, nelfinavir: Reduced absorption. Methotrexate: Increased levels.',
    overdose_info: 'No specific antidote. Symptomatic treatment.',
    pregnancy_category: 'B',
    lactation_info: 'Excreted in breast milk. Caution advised.',
    storage: 'Store below 25°C. Protect from moisture.',
  },

  // ========== ANTIBIOTICS ==========
  {
    name: 'Azithral 500',
    generic_name: 'Azithromycin',
    dosage_form: 'Tablet',
    strength: '500mg',
    manufacturer_name: 'Incepta Pharmaceuticals Ltd.',
    unit_price: 35.00,
    strip_price: 105.00,
    pack_size: '3 tablets/strip',
    drug_class: 'Macrolide Antibiotic',
    therapeutic_class: 'Antibacterials',
    indication: 'Respiratory tract infections, skin and soft tissue infections, sexually transmitted diseases, otitis media.',
    pharmacology: 'Azithromycin is an azalide antibiotic derived from erythromycin. It binds to the 50S ribosomal subunit of susceptible microorganisms and interferes with bacterial protein synthesis.',
    mode_of_action: 'Binds to 23S rRNA of the 50S ribosomal subunit, inhibiting bacterial protein synthesis.',
    dosage_adult: '500mg once daily for 3 days, or 500mg on day 1 followed by 250mg on days 2-5.',
    dosage_pediatric: '10 mg/kg once daily for 3 days.',
    administration: 'Take 1 hour before or 2 hours after meals for optimal absorption. Can be taken with food if GI upset occurs.',
    contraindications: 'Hypersensitivity to azithromycin, erythromycin, or any macrolide antibiotics. History of cholestatic jaundice with prior azithromycin use.',
    side_effects: 'Common: Diarrhea, nausea, abdominal pain. Rare: QT prolongation, hepatotoxicity, allergic reactions.',
    precautions: 'Caution in patients with hepatic dysfunction, QT prolongation, or myasthenia gravis.',
    drug_interactions: 'Antacids: Take 1 hour before or 2 hours after. Warfarin: Monitor INR. Digoxin: Increased digoxin levels.',
    overdose_info: 'No specific antidote. Gastric lavage and supportive measures.',
    pregnancy_category: 'B',
    lactation_info: 'Use with caution. Excreted in breast milk.',
    storage: 'Store below 30°C. Protect from light.',
  },
  {
    name: 'Ciprocin 500',
    generic_name: 'Ciprofloxacin',
    dosage_form: 'Tablet',
    strength: '500mg',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 8.00,
    strip_price: 80.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Fluoroquinolone',
    therapeutic_class: 'Antibacterials',
    indication: 'UTI, respiratory tract infections, GI infections, bone and joint infections, skin infections.',
    pharmacology: 'Ciprofloxacin is a fluoroquinolone antibiotic that inhibits bacterial DNA gyrase and topoisomerase IV, enzymes essential for DNA replication.',
    mode_of_action: 'Inhibits DNA gyrase and topoisomerase IV, preventing bacterial DNA replication and transcription.',
    dosage_adult: '250-750mg twice daily depending on infection severity.',
    dosage_pediatric: 'Not recommended for children due to risk of cartilage damage.',
    administration: 'Take 2 hours before or 6 hours after antacids. Maintain adequate hydration.',
    contraindications: 'Hypersensitivity to fluoroquinolones. Concurrent tizanidine use.',
    side_effects: 'GI disturbances, headache, dizziness. Rare: Tendon rupture, QT prolongation, peripheral neuropathy.',
    precautions: 'Risk of tendinitis (especially in elderly, corticosteroid users). Avoid excessive sun exposure.',
    drug_interactions: 'Theophylline: Increased theophylline levels. Antacids, iron, zinc: Reduced ciprofloxacin absorption.',
    overdose_info: 'Maintain hydration, supportive care. Hemodialysis removes limited amount.',
    pregnancy_category: 'C',
    lactation_info: 'Not recommended during breastfeeding.',
    storage: 'Store below 30°C. Protect from light.',
  },
  {
    name: 'Cef-3 200',
    generic_name: 'Cefixime',
    dosage_form: 'Capsule',
    strength: '200mg',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 25.00,
    strip_price: 250.00,
    pack_size: '10 capsules/strip',
    drug_class: 'Cephalosporin (3rd Generation)',
    therapeutic_class: 'Antibacterials',
    indication: 'Respiratory tract infections, urinary tract infections, gonorrhea, otitis media.',
    pharmacology: 'Cefixime is a third-generation oral cephalosporin antibiotic with extended spectrum activity against gram-negative bacteria.',
    mode_of_action: 'Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins (PBPs).',
    dosage_adult: '200mg twice daily or 400mg once daily for 7-14 days.',
    dosage_pediatric: '8 mg/kg/day in 1-2 divided doses.',
    administration: 'May be taken with or without food.',
    contraindications: 'Hypersensitivity to cephalosporins or penicillins (cross-reactivity possible).',
    side_effects: 'Diarrhea, nausea, abdominal pain, dyspepsia. Rare: Pseudomembranous colitis.',
    precautions: 'Adjust dose in renal impairment. Monitor for superinfection.',
    drug_interactions: 'Probenecid: Increased cefixime levels. Oral anticoagulants: Monitor PT/INR.',
    overdose_info: 'Supportive care. Hemodialysis may be helpful.',
    pregnancy_category: 'B',
    lactation_info: 'Excreted in breast milk. Use with caution.',
    storage: 'Store below 25°C. Protect from moisture.',
  },
  {
    name: 'Amoxil 500',
    generic_name: 'Amoxicillin',
    dosage_form: 'Capsule',
    strength: '500mg',
    manufacturer_name: 'GlaxoSmithKline Bangladesh',
    unit_price: 8.00,
    strip_price: 80.00,
    pack_size: '10 capsules/strip',
    drug_class: 'Aminopenicillin',
    therapeutic_class: 'Antibacterials',
    indication: 'Respiratory tract infections, ear infections, UTI, H. pylori eradication, skin infections.',
    pharmacology: 'Amoxicillin is a semi-synthetic aminopenicillin antibiotic with broad-spectrum activity against many gram-positive and gram-negative organisms.',
    mode_of_action: 'Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins.',
    dosage_adult: '250-500mg every 8 hours, or 500-875mg every 12 hours.',
    dosage_pediatric: '20-40 mg/kg/day in divided doses every 8 hours.',
    administration: 'May be taken with or without food. Take with food to reduce GI upset.',
    contraindications: 'Penicillin allergy. Infectious mononucleosis (risk of rash).',
    side_effects: 'Diarrhea, nausea, skin rash. Rare: Anaphylaxis, C. difficile colitis.',
    precautions: 'Monitor for allergic reactions. Adjust dose in renal impairment.',
    drug_interactions: 'Allopurinol: Increased rash risk. Oral contraceptives: May reduce efficacy.',
    overdose_info: 'GI symptoms. Hemodialysis can remove amoxicillin.',
    pregnancy_category: 'B',
    lactation_info: 'Compatible with breastfeeding.',
    storage: 'Store below 25°C. Protect from moisture.',
  },

  // ========== ANTIHYPERTENSIVES ==========
  {
    name: 'Amlopin 5',
    generic_name: 'Amlodipine',
    dosage_form: 'Tablet',
    strength: '5mg',
    manufacturer_name: 'Renata Limited',
    unit_price: 3.00,
    strip_price: 30.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Calcium Channel Blocker',
    therapeutic_class: 'Antihypertensives',
    indication: 'Hypertension, chronic stable angina, vasospastic angina.',
    pharmacology: 'Amlodipine is a dihydropyridine calcium channel blocker that inhibits transmembrane influx of calcium ions into vascular smooth muscle and cardiac muscle.',
    mode_of_action: 'Blocks L-type calcium channels in vascular smooth muscle, causing vasodilation and reduced peripheral resistance.',
    dosage_adult: '5-10mg once daily.',
    dosage_pediatric: '2.5-5mg once daily for children 6-17 years.',
    administration: 'Oral. May be taken with or without food.',
    contraindications: 'Hypersensitivity to amlodipine or dihydropyridines. Severe hypotension, cardiogenic shock.',
    side_effects: 'Common: Peripheral edema, flushing, headache, dizziness. Rare: Gingival hyperplasia.',
    precautions: 'Severe aortic stenosis, hepatic impairment.',
    drug_interactions: 'CYP3A4 inhibitors may increase amlodipine levels. Simvastatin: Limit simvastatin dose.',
    overdose_info: 'Hypotension, tachycardia. Supportive treatment including IV calcium gluconate.',
    pregnancy_category: 'C',
    lactation_info: 'Not recommended during breastfeeding.',
    storage: 'Store below 30°C. Protect from light and moisture.',
  },
  {
    name: 'Loazin 50',
    generic_name: 'Losartan Potassium',
    dosage_form: 'Tablet',
    strength: '50mg',
    manufacturer_name: 'Beximco Pharmaceuticals Ltd.',
    unit_price: 6.00,
    strip_price: 60.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Angiotensin II Receptor Blocker',
    therapeutic_class: 'Antihypertensives',
    indication: 'Hypertension, diabetic nephropathy in type 2 diabetes, stroke risk reduction in hypertensive patients with LVH.',
    pharmacology: 'Losartan is an angiotensin II receptor antagonist that blocks the vasoconstrictor and aldosterone-secreting effects of angiotensin II.',
    mode_of_action: 'Selectively blocks the binding of angiotensin II to AT1 receptors in vascular smooth muscle.',
    dosage_adult: '50-100mg once daily.',
    dosage_pediatric: '0.7 mg/kg once daily for children 6 years and older.',
    administration: 'May be taken with or without food.',
    contraindications: 'Pregnancy, hypersensitivity to losartan. Concurrent use with aliskiren in diabetic patients.',
    side_effects: 'Dizziness, hyperkalemia, hypotension, renal impairment.',
    precautions: 'Monitor potassium and renal function. Avoid in bilateral renal artery stenosis.',
    drug_interactions: 'NSAIDs: Reduced antihypertensive effect. Potassium supplements: Hyperkalemia risk.',
    overdose_info: 'Hypotension, tachycardia. Supportive treatment.',
    pregnancy_category: 'D',
    lactation_info: 'Not recommended. Unknown if excreted in breast milk.',
    storage: 'Store below 30°C. Protect from light.',
  },
  {
    name: 'Lisoril 5',
    generic_name: 'Lisinopril',
    dosage_form: 'Tablet',
    strength: '5mg',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 4.00,
    strip_price: 40.00,
    pack_size: '10 tablets/strip',
    drug_class: 'ACE Inhibitor',
    therapeutic_class: 'Antihypertensives',
    indication: 'Hypertension, heart failure, post-MI, diabetic nephropathy.',
    pharmacology: 'Lisinopril is an angiotensin-converting enzyme (ACE) inhibitor that prevents conversion of angiotensin I to angiotensin II.',
    mode_of_action: 'Inhibits ACE, reducing angiotensin II and aldosterone levels, causing vasodilation.',
    dosage_adult: '5-40mg once daily.',
    dosage_pediatric: '0.07 mg/kg once daily for children 6 years and older.',
    administration: 'May be taken with or without food.',
    contraindications: 'History of angioedema with ACE inhibitors, pregnancy, bilateral renal artery stenosis.',
    side_effects: 'Dry cough, hyperkalemia, angioedema, hypotension, renal impairment.',
    precautions: 'Monitor potassium and renal function. Risk of angioedema.',
    drug_interactions: 'Potassium supplements, NSAIDs, lithium.',
    overdose_info: 'Hypotension. Supportive care, IV fluids.',
    pregnancy_category: 'D',
    lactation_info: 'Not recommended.',
    storage: 'Store below 30°C. Protect from moisture.',
  },

  // ========== ANTIDIABETICS ==========
  {
    name: 'Comet 500',
    generic_name: 'Metformin HCl',
    dosage_form: 'Tablet',
    strength: '500mg',
    manufacturer_name: 'Healthcare Pharmaceuticals Ltd.',
    unit_price: 2.50,
    strip_price: 50.00,
    pack_size: '20 tablets/strip',
    drug_class: 'Biguanide',
    therapeutic_class: 'Antidiabetic Agents',
    indication: 'Type 2 diabetes mellitus, polycystic ovary syndrome (PCOS).',
    pharmacology: 'Metformin is a biguanide antihyperglycemic agent that decreases hepatic glucose production, decreases intestinal absorption of glucose, and improves insulin sensitivity.',
    mode_of_action: 'Activates AMP-activated protein kinase (AMPK), suppressing hepatic gluconeogenesis and increasing peripheral glucose uptake.',
    dosage_adult: '500mg twice daily initially, increase gradually. Maximum 2550mg/day in divided doses.',
    dosage_pediatric: '500mg twice daily for children ≥10 years. Maximum 2000mg/day.',
    administration: 'Take with meals to reduce GI side effects.',
    contraindications: 'Diabetic ketoacidosis, renal impairment (eGFR <30), metabolic acidosis, dehydration.',
    side_effects: 'Common: GI upset (diarrhea, nausea, vomiting), metallic taste. Rare: Lactic acidosis, vitamin B12 deficiency.',
    precautions: 'Discontinue before iodinated contrast procedures. Monitor renal function regularly.',
    drug_interactions: 'Alcohol: Increased risk of lactic acidosis. Iodinated contrast: Discontinue metformin.',
    overdose_info: 'Lactic acidosis is rare but serious. Hemodialysis is effective for removal.',
    pregnancy_category: 'B',
    lactation_info: 'Compatible with breastfeeding.',
    storage: 'Store below 30°C.',
  },
  {
    name: 'Glipid 5',
    generic_name: 'Glipizide',
    dosage_form: 'Tablet',
    strength: '5mg',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 3.00,
    strip_price: 30.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Sulfonylurea',
    therapeutic_class: 'Antidiabetic Agents',
    indication: 'Type 2 diabetes mellitus as adjunct to diet and exercise.',
    pharmacology: 'Glipizide is a second-generation sulfonylurea that stimulates insulin release from pancreatic beta cells.',
    mode_of_action: 'Binds to sulfonylurea receptors on pancreatic beta cells, closing ATP-sensitive K+ channels and stimulating insulin secretion.',
    dosage_adult: '5mg daily before breakfast, may increase to 40mg/day in divided doses.',
    dosage_pediatric: 'Not established.',
    administration: 'Take 30 minutes before meals.',
    contraindications: 'Type 1 diabetes, diabetic ketoacidosis, sulfonamide allergy.',
    side_effects: 'Hypoglycemia, weight gain, GI disturbances.',
    precautions: 'Elderly at higher risk of hypoglycemia. Hepatic/renal impairment.',
    drug_interactions: 'Beta-blockers may mask hypoglycemia symptoms. Alcohol: Disulfiram-like reaction possible.',
    overdose_info: 'Prolonged hypoglycemia. IV dextrose, glucagon.',
    pregnancy_category: 'C',
    lactation_info: 'Not recommended.',
    storage: 'Store below 30°C. Protect from moisture.',
  },

  // ========== RESPIRATORY ==========
  {
    name: 'Montair 10',
    generic_name: 'Montelukast',
    dosage_form: 'Tablet',
    strength: '10mg',
    manufacturer_name: 'ACI Limited',
    unit_price: 12.00,
    strip_price: 120.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Leukotriene Receptor Antagonist',
    therapeutic_class: 'Anti-Asthmatic Drugs',
    indication: 'Prophylaxis and chronic treatment of asthma, allergic rhinitis, exercise-induced bronchoconstriction.',
    pharmacology: 'Montelukast is a selective leukotriene receptor antagonist that blocks the CysLT1 receptor, inhibiting the effects of cysteinyl leukotrienes.',
    mode_of_action: 'Blocks CysLT1 receptors in the airways, reducing bronchoconstriction, mucus secretion, and airway inflammation.',
    dosage_adult: '10mg once daily in the evening.',
    dosage_pediatric: '4mg (2-5 years), 5mg (6-14 years) chewable tablets once daily in the evening.',
    administration: 'Take in the evening for asthma. Can be taken with or without food.',
    contraindications: 'Hypersensitivity to montelukast.',
    side_effects: 'Headache, abdominal pain, thirst. Rare: Neuropsychiatric events (agitation, depression, suicidal thinking).',
    precautions: 'Not for acute asthma attacks. Monitor for behavioral changes.',
    drug_interactions: 'Phenobarbital, rifampicin: May reduce montelukast levels.',
    overdose_info: 'No specific data. Provide supportive care.',
    pregnancy_category: 'B',
    lactation_info: 'Excreted in breast milk. Use with caution.',
    storage: 'Store below 30°C. Protect from light and moisture.',
  },
  {
    name: 'Salbuvent Inhaler',
    generic_name: 'Salbutamol',
    dosage_form: 'Inhaler',
    strength: '100mcg/puff',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 180.00,
    strip_price: null,
    pack_size: '200 puffs',
    drug_class: 'Beta-2 Agonist (SABA)',
    therapeutic_class: 'Bronchodilators',
    indication: 'Relief of acute bronchospasm in asthma, COPD, exercise-induced bronchospasm.',
    pharmacology: 'Salbutamol is a selective beta-2 adrenergic receptor agonist that relaxes bronchial smooth muscle.',
    mode_of_action: 'Stimulates beta-2 receptors in bronchial smooth muscle, increasing cAMP and causing bronchodilation.',
    dosage_adult: '1-2 puffs every 4-6 hours as needed.',
    dosage_pediatric: '1 puff every 4-6 hours as needed for children over 4 years.',
    administration: 'Inhale through mouth. Shake well before use. Use spacer device if available.',
    contraindications: 'Hypersensitivity to salbutamol.',
    side_effects: 'Tremor, palpitations, headache, tachycardia.',
    precautions: 'Cardiovascular disease, hyperthyroidism, diabetes.',
    drug_interactions: 'Beta-blockers: Reduced bronchodilator effect. MAO inhibitors: Enhanced cardiovascular effects.',
    overdose_info: 'Tremor, tachycardia, hypokalemia. Supportive care.',
    pregnancy_category: 'C',
    lactation_info: 'Probably compatible with breastfeeding.',
    storage: 'Store below 30°C. Protect from sunlight. Do not puncture or burn.',
  },

  // ========== ANTIHISTAMINES ==========
  {
    name: 'Alatrol 10',
    generic_name: 'Cetirizine',
    dosage_form: 'Tablet',
    strength: '10mg',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 3.00,
    strip_price: 30.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Second-Generation Antihistamine',
    therapeutic_class: 'Antiallergics',
    indication: 'Allergic rhinitis, chronic urticaria, allergic conjunctivitis.',
    pharmacology: 'Cetirizine is a second-generation piperazine antihistamine with minimal anticholinergic and sedative effects.',
    mode_of_action: 'Selectively blocks peripheral H1 receptors, reducing histamine-mediated allergic symptoms.',
    dosage_adult: '10mg once daily.',
    dosage_pediatric: '2.5mg (2-5 years), 5-10mg (6-12 years) once daily.',
    administration: 'May be taken with or without food.',
    contraindications: 'Hypersensitivity to cetirizine or hydroxyzine.',
    side_effects: 'Mild drowsiness, dry mouth, headache, fatigue.',
    precautions: 'Renal impairment (reduce dose). May cause drowsiness in some patients.',
    drug_interactions: 'CNS depressants: Additive sedation. Theophylline: Slight decrease in cetirizine clearance.',
    overdose_info: 'Drowsiness, restlessness. Supportive care.',
    pregnancy_category: 'B',
    lactation_info: 'Excreted in breast milk. Use with caution.',
    storage: 'Store below 30°C.',
  },
  {
    name: 'Fexo 120',
    generic_name: 'Fexofenadine',
    dosage_form: 'Tablet',
    strength: '120mg',
    manufacturer_name: 'Renata Limited',
    unit_price: 8.00,
    strip_price: 80.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Second-Generation Antihistamine',
    therapeutic_class: 'Antiallergics',
    indication: 'Seasonal allergic rhinitis, chronic idiopathic urticaria.',
    pharmacology: 'Fexofenadine is a non-sedating second-generation antihistamine, the active metabolite of terfenadine without cardiotoxic effects.',
    mode_of_action: 'Selective peripheral H1 receptor antagonist without significant CNS or cardiac effects.',
    dosage_adult: '120mg once daily for allergic rhinitis, 180mg once daily for urticaria.',
    dosage_pediatric: '30mg twice daily for children 6-11 years.',
    administration: 'Take with water. Avoid fruit juices (may reduce absorption).',
    contraindications: 'Hypersensitivity to fexofenadine.',
    side_effects: 'Headache, drowsiness, nausea, dysmenorrhea.',
    precautions: 'Reduce dose in renal impairment.',
    drug_interactions: 'Antacids: Reduced absorption (take 2 hours apart). Erythromycin, ketoconazole: Increased fexofenadine levels.',
    overdose_info: 'Dizziness, drowsiness, dry mouth. Supportive care.',
    pregnancy_category: 'C',
    lactation_info: 'Use with caution.',
    storage: 'Store below 25°C. Protect from moisture.',
  },

  // ========== VITAMINS & SUPPLEMENTS ==========
  {
    name: 'Calbo-D',
    generic_name: 'Calcium Carbonate + Vitamin D3',
    dosage_form: 'Tablet',
    strength: '500mg + 200IU',
    manufacturer_name: 'Square Pharmaceuticals Ltd.',
    unit_price: 5.00,
    strip_price: 50.00,
    pack_size: '10 tablets/strip',
    drug_class: 'Calcium & Vitamin D Supplement',
    therapeutic_class: 'Bone Health Supplements',
    indication: 'Prevention and treatment of calcium and vitamin D deficiency, osteoporosis prevention.',
    pharmacology: 'Calcium is essential for bone mineralization. Vitamin D3 enhances intestinal calcium absorption and bone formation.',
    mode_of_action: 'Provides elemental calcium for bone matrix. Vitamin D3 increases calcium absorption and bone deposition.',
    dosage_adult: '1-2 tablets daily with meals.',
    dosage_pediatric: 'As directed by physician.',
    administration: 'Take with food for optimal absorption. Chew or swallow with water.',
    contraindications: 'Hypercalcemia, hypervitaminosis D, renal calculi.',
    side_effects: 'Constipation, bloating, nausea. Rare: Hypercalcemia with high doses.',
    precautions: 'Monitor calcium levels in renal impairment. Avoid excessive vitamin D intake.',
    drug_interactions: 'Tetracyclines, fluoroquinolones: Reduced absorption (separate by 2-3 hours). Thiazides: Increased hypercalcemia risk.',
    overdose_info: 'Hypercalcemia symptoms: Weakness, confusion, polyuria. Discontinue and hydrate.',
    pregnancy_category: 'A',
    lactation_info: 'Compatible with breastfeeding at recommended doses.',
    storage: 'Store below 30°C. Protect from moisture.',
  },
  {
    name: 'Ferrous Plus',
    generic_name: 'Ferrous Sulfate + Folic Acid',
    dosage_form: 'Tablet',
    strength: '200mg + 0.5mg',
    manufacturer_name: 'ACI Limited',
    unit_price: 2.00,
    strip_price: 40.00,
    pack_size: '20 tablets/strip',
    drug_class: 'Iron Supplement',
    therapeutic_class: 'Haematinics',
    indication: 'Iron deficiency anemia, pregnancy-related anemia, folic acid deficiency.',
    pharmacology: 'Ferrous sulfate provides elemental iron for hemoglobin synthesis. Folic acid is essential for DNA synthesis and red blood cell maturation.',
    mode_of_action: 'Iron is incorporated into hemoglobin. Folic acid acts as coenzyme in nucleotide synthesis.',
    dosage_adult: '1 tablet 1-2 times daily.',
    dosage_pediatric: 'As directed by physician.',
    administration: 'Take on empty stomach for best absorption. May take with food if GI upset occurs.',
    contraindications: 'Hemochromatosis, hemosiderosis, hemolytic anemias.',
    side_effects: 'GI upset, constipation, dark stools, nausea.',
    precautions: 'Keep away from children (iron poisoning risk). Monitor for iron overload.',
    drug_interactions: 'Antacids, tetracyclines, fluoroquinolones: Reduced iron absorption.',
    overdose_info: 'Iron toxicity: GI bleeding, shock. Deferoxamine is the antidote.',
    pregnancy_category: 'A',
    lactation_info: 'Compatible with breastfeeding.',
    storage: 'Store below 30°C. Protect from moisture.',
  },
];

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('Starting MedEx-style medicine import...');

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Fetch existing medicine names to avoid duplicates
    const { data: existingMedicines, error: fetchError } = await supabase
      .from('medicine_reference')
      .select('name');

    if (fetchError) {
      console.error('Error fetching existing medicines:', fetchError);
      throw fetchError;
    }

    const existingNames = new Set(
      (existingMedicines || []).map((m: { name: string }) => m.name.toLowerCase())
    );

    console.log(`Existing medicines in database: ${existingNames.size}`);

    // Filter out existing medicines
    const medicinesToInsert = MEDICINES_DATA
      .filter(med => !existingNames.has(med.name.toLowerCase()))
      .map(med => ({
        name: med.name,
        generic_name: med.generic_name,
        dosage_form: med.dosage_form,
        strength: med.strength,
        manufacturer_name: med.manufacturer_name,
        unit_price: med.unit_price,
        strip_price: med.strip_price,
        pack_size: med.pack_size,
        drug_class: med.drug_class,
        therapeutic_class: med.therapeutic_class,
        indication: med.indication,
        pharmacology: med.pharmacology,
        mode_of_action: med.mode_of_action,
        dosage_adult: med.dosage_adult,
        dosage_pediatric: med.dosage_pediatric,
        administration: med.administration,
        contraindications: med.contraindications,
        side_effects: med.side_effects,
        precautions: med.precautions,
        drug_interactions: med.drug_interactions,
        overdose_info: med.overdose_info,
        pregnancy_category: med.pregnancy_category,
        lactation_info: med.lactation_info,
        storage: med.storage,
        is_active: true,
      }));

    console.log(`New medicines to insert: ${medicinesToInsert.length}`);

    if (medicinesToInsert.length === 0) {
      return new Response(
        JSON.stringify({
          success: true,
          message: 'All sample medicines already exist',
          inserted: 0,
          skipped: MEDICINES_DATA.length,
          total: existingNames.size,
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Insert medicines in batches
    const BATCH_SIZE = 10;
    let totalInserted = 0;

    for (let i = 0; i < medicinesToInsert.length; i += BATCH_SIZE) {
      const batch = medicinesToInsert.slice(i, i + BATCH_SIZE);
      const { error: insertError } = await supabase
        .from('medicine_reference')
        .insert(batch);

      if (insertError) {
        console.error(`Error inserting batch ${Math.floor(i / BATCH_SIZE) + 1}:`, insertError);
        throw insertError;
      }

      totalInserted += batch.length;
      console.log(`Inserted batch ${Math.floor(i / BATCH_SIZE) + 1}: ${batch.length} medicines`);
    }

    const skipped = MEDICINES_DATA.length - totalInserted;

    return new Response(
      JSON.stringify({
        success: true,
        message: `Successfully imported ${totalInserted} MedEx-style medicines`,
        inserted: totalInserted,
        skipped: skipped,
        total: existingNames.size + totalInserted,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: unknown) {
    console.error('Error importing medicines:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to import medicines';
    return new Response(
      JSON.stringify({
        success: false,
        error: errorMessage,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
