-- Insert sample MedEx-style medicine data for testing
INSERT INTO medicine_reference (
  name, generic_name, dosage_form, strength, manufacturer_name,
  unit_price, strip_price, pack_size, drug_class, therapeutic_class,
  indication, pharmacology, mode_of_action,
  dosage_adult, dosage_pediatric, administration,
  contraindications, side_effects, precautions, drug_interactions,
  overdose_info, pregnancy_category, lactation_info, storage, is_active
) VALUES 
-- Napa 500mg (Paracetamol)
(
  'Napa 500', 'Paracetamol', 'Tablet', '500mg', 'Beximco Pharmaceuticals Ltd.',
  2.50, 25.00, '10 tablets/strip', 'Analgesic & Antipyretic', 'Non-Opioid Analgesics',
  'Fever, mild to moderate pain including headache, toothache, backache, migraine, neuralgia, muscle aches, period pain, post-operative pain.',
  'Paracetamol is a para-aminophenol derivative that exhibits analgesic and antipyretic activity. It does not possess anti-inflammatory activity. The mechanism of action is not fully understood but may involve inhibition of prostaglandin synthesis in the CNS.',
  'Inhibits prostaglandin synthesis centrally by blocking COX enzymes, reducing fever via action on the hypothalamic heat-regulating center.',
  '500mg-1g every 4-6 hours as needed. Maximum 4g daily.',
  '10-15 mg/kg every 4-6 hours. Maximum 5 doses in 24 hours.',
  'Oral administration. Can be taken with or without food.',
  'Hypersensitivity to paracetamol. Severe hepatic impairment.',
  'Rare: Skin rashes, blood dyscrasias (thrombocytopenia, agranulocytosis). Hepatotoxicity with overdose.',
  'Use with caution in hepatic impairment, chronic alcohol use, dehydration, and chronic malnutrition.',
  'Warfarin: May enhance anticoagulant effect. Metoclopramide: Increases absorption rate. Cholestyramine: Reduces absorption.',
  'Overdose can cause severe hepatotoxicity. Symptoms include nausea, vomiting, abdominal pain. N-acetylcysteine is the specific antidote.',
  'B', 'Compatible with breastfeeding. Excreted in breast milk in small amounts.',
  'Store below 30°C. Protect from light and moisture.', true
),
-- Seclo 20mg (Omeprazole)
(
  'Seclo 20', 'Omeprazole', 'Capsule', '20mg', 'Square Pharmaceuticals Ltd.',
  6.00, 60.00, '10 capsules/strip', 'Proton Pump Inhibitor', 'Anti-Ulcerant Drugs',
  'Gastric ulcer, duodenal ulcer, GERD, Zollinger-Ellison syndrome, H. pylori eradication (with antibiotics), NSAID-associated gastric ulcer.',
  'Omeprazole is a substituted benzimidazole that suppresses gastric acid secretion by specific inhibition of the H+/K+ ATPase enzyme system at the secretory surface of the gastric parietal cell.',
  'Irreversibly inhibits the proton pump (H+/K+ ATPase) in parietal cells, blocking the final step of acid production.',
  '20-40mg once daily for 4-8 weeks. Maintenance: 10-20mg daily.',
  '0.7-3.3 mg/kg/day for children over 1 year.',
  'Take before meals, preferably in the morning. Swallow capsule whole, do not crush or chew.',
  'Hypersensitivity to omeprazole or other proton pump inhibitors.',
  'Common: Headache, diarrhea, nausea, abdominal pain. Rare: Vitamin B12 deficiency, hypomagnesemia with prolonged use.',
  'Long-term use may increase risk of bone fractures, Clostridium difficile infection, and vitamin B12 deficiency.',
  'Clopidogrel: Reduced antiplatelet effect. Methotrexate: Increased methotrexate levels. Ketoconazole: Decreased absorption.',
  'Symptoms are transient. Treatment is supportive and symptomatic.',
  'C', 'Not recommended during breastfeeding as omeprazole is excreted in breast milk.',
  'Store below 25°C in a dry place. Protect from light.', true
),
-- Ace 500mg (Paracetamol - different brand)
(
  'Ace 500', 'Paracetamol', 'Tablet', '500mg', 'Square Pharmaceuticals Ltd.',
  2.00, 20.00, '10 tablets/strip', 'Analgesic & Antipyretic', 'Non-Opioid Analgesics',
  'Fever, mild to moderate pain including headache, toothache, backache, migraine, neuralgia, muscle aches.',
  'Paracetamol is a para-aminophenol derivative that exhibits analgesic and antipyretic activity without significant anti-inflammatory action.',
  'Acts primarily in the CNS, inhibiting prostaglandin synthesis and blocking pain impulse generation peripherally.',
  '500mg-1g every 4-6 hours as needed. Maximum 4g daily.',
  '10-15 mg/kg every 4-6 hours. Maximum 5 doses in 24 hours.',
  'Oral. May be taken with or without food.',
  'Hypersensitivity to paracetamol. Severe hepatic impairment.',
  'Rare: Allergic skin reactions, blood disorders.',
  'Hepatic impairment, chronic alcoholism, dehydration.',
  'Warfarin, Metoclopramide, Cholestyramine.',
  'Hepatotoxicity with overdose. N-acetylcysteine is the antidote.',
  'B', 'Safe during breastfeeding.',
  'Store below 30°C.', true
),
-- Azithral 500mg (Azithromycin)
(
  'Azithral 500', 'Azithromycin', 'Tablet', '500mg', 'Incepta Pharmaceuticals Ltd.',
  35.00, 105.00, '3 tablets/strip', 'Macrolide Antibiotic', 'Antibacterials',
  'Respiratory tract infections, skin and soft tissue infections, sexually transmitted diseases, otitis media.',
  'Azithromycin is an azalide antibiotic derived from erythromycin. It binds to the 50S ribosomal subunit of susceptible microorganisms and interferes with bacterial protein synthesis.',
  'Binds to 23S rRNA of the 50S ribosomal subunit, inhibiting bacterial protein synthesis.',
  '500mg once daily for 3 days, or 500mg on day 1 followed by 250mg on days 2-5.',
  '10 mg/kg once daily for 3 days.',
  'Take 1 hour before or 2 hours after meals for optimal absorption. Can be taken with food if GI upset occurs.',
  'Hypersensitivity to azithromycin, erythromycin, or any macrolide antibiotics. History of cholestatic jaundice with prior azithromycin use.',
  'Common: Diarrhea, nausea, abdominal pain. Rare: QT prolongation, hepatotoxicity, allergic reactions.',
  'Caution in patients with hepatic dysfunction, QT prolongation, or myasthenia gravis.',
  'Antacids: Take 1 hour before or 2 hours after. Warfarin: Monitor INR. Digoxin: Increased digoxin levels.',
  'No specific antidote. Gastric lavage and supportive measures.',
  'B', 'Use with caution. Excreted in breast milk.',
  'Store below 30°C. Protect from light.', true
),
-- Losectil 20mg (Esomeprazole)
(
  'Losectil 20', 'Esomeprazole', 'Capsule', '20mg', 'Eskayef Pharmaceuticals Ltd.',
  8.00, 80.00, '10 capsules/strip', 'Proton Pump Inhibitor', 'Anti-Ulcerant Drugs',
  'GERD, erosive esophagitis, peptic ulcer, H. pylori eradication, Zollinger-Ellison syndrome.',
  'Esomeprazole is the S-isomer of omeprazole. It suppresses gastric acid secretion by specifically inhibiting the H+/K+-ATPase in gastric parietal cells.',
  'Specifically inhibits the proton pump in parietal cells, providing potent and sustained acid suppression.',
  '20-40mg once daily.',
  '10-20mg once daily for children 1-11 years weighing ≥20kg.',
  'Take at least 1 hour before meals. Swallow whole.',
  'Hypersensitivity to esomeprazole or substituted benzimidazoles.',
  'Headache, diarrhea, nausea, flatulence, abdominal pain.',
  'Long-term use: Risk of bone fractures, hypomagnesemia, vitamin B12 deficiency.',
  'Clopidogrel, methotrexate, ketoconazole, HIV protease inhibitors.',
  'Symptoms are transient. Provide supportive care.',
  'C', 'Caution advised. Present in breast milk.',
  'Store below 25°C.', true
),
-- Amlodipine 5mg
(
  'Amlopin 5', 'Amlodipine', 'Tablet', '5mg', 'Renata Limited',
  3.00, 30.00, '10 tablets/strip', 'Calcium Channel Blocker', 'Antihypertensives',
  'Hypertension, chronic stable angina, vasospastic angina.',
  'Amlodipine is a dihydropyridine calcium channel blocker that inhibits transmembrane influx of calcium ions into vascular smooth muscle and cardiac muscle.',
  'Blocks L-type calcium channels in vascular smooth muscle, causing vasodilation and reduced peripheral resistance.',
  '5-10mg once daily.',
  '2.5-5mg once daily for children 6-17 years.',
  'Oral. May be taken with or without food.',
  'Hypersensitivity to amlodipine or dihydropyridines. Severe hypotension, cardiogenic shock.',
  'Common: Peripheral edema, flushing, headache, dizziness. Rare: Gingival hyperplasia.',
  'Severe aortic stenosis, hepatic impairment.',
  'CYP3A4 inhibitors may increase amlodipine levels. Simvastatin: Limit simvastatin dose.',
  'Hypotension, tachycardia. Supportive treatment including IV calcium gluconate.',
  'C', 'Not recommended during breastfeeding.',
  'Store below 30°C. Protect from light and moisture.', true
),
-- Metformin 500mg
(
  'Comet 500', 'Metformin HCl', 'Tablet', '500mg', 'Healthcare Pharmaceuticals Ltd.',
  2.50, 50.00, '20 tablets/strip', 'Biguanide', 'Antidiabetic Agents',
  'Type 2 diabetes mellitus, polycystic ovary syndrome (PCOS).',
  'Metformin is a biguanide antihyperglycemic agent that decreases hepatic glucose production, decreases intestinal absorption of glucose, and improves insulin sensitivity.',
  'Activates AMP-activated protein kinase (AMPK), suppressing hepatic gluconeogenesis and increasing peripheral glucose uptake.',
  '500mg twice daily initially, increase gradually. Maximum 2550mg/day in divided doses.',
  '500mg twice daily for children ≥10 years. Maximum 2000mg/day.',
  'Take with meals to reduce GI side effects.',
  'Diabetic ketoacidosis, renal impairment (eGFR <30), metabolic acidosis, dehydration.',
  'Common: GI upset (diarrhea, nausea, vomiting), metallic taste. Rare: Lactic acidosis, vitamin B12 deficiency.',
  'Discontinue before iodinated contrast procedures. Monitor renal function regularly.',
  'Alcohol: Increased risk of lactic acidosis. Iodinated contrast: Discontinue metformin.',
  'Lactic acidosis is rare but serious. Hemodialysis is effective for removal.',
  'B', 'Compatible with breastfeeding.',
  'Store below 30°C.', true
),
-- Ciprofloxacin 500mg
(
  'Ciprocin 500', 'Ciprofloxacin', 'Tablet', '500mg', 'Square Pharmaceuticals Ltd.',
  8.00, 80.00, '10 tablets/strip', 'Fluoroquinolone', 'Antibacterials',
  'UTI, respiratory tract infections, GI infections, bone and joint infections, skin infections.',
  'Ciprofloxacin is a fluoroquinolone antibiotic that inhibits bacterial DNA gyrase and topoisomerase IV, enzymes essential for DNA replication.',
  'Inhibits DNA gyrase and topoisomerase IV, preventing bacterial DNA replication and transcription.',
  '250-750mg twice daily depending on infection severity.',
  'Not recommended for children due to risk of cartilage damage.',
  'Take 2 hours before or 6 hours after antacids. Maintain adequate hydration.',
  'Hypersensitivity to fluoroquinolones. Concurrent tizanidine use.',
  'GI disturbances, headache, dizziness. Rare: Tendon rupture, QT prolongation, peripheral neuropathy.',
  'Risk of tendinitis (especially in elderly, corticosteroid users). Avoid excessive sun exposure.',
  'Theophylline: Increased theophylline levels. Antacids, iron, zinc: Reduced ciprofloxacin absorption.',
  'Maintain hydration, supportive care. Hemodialysis removes limited amount.',
  'C', 'Not recommended during breastfeeding.',
  'Store below 30°C. Protect from light.', true
),
-- Montelukast 10mg
(
  'Montair 10', 'Montelukast', 'Tablet', '10mg', 'ACI Limited',
  12.00, 120.00, '10 tablets/strip', 'Leukotriene Receptor Antagonist', 'Anti-Asthmatic Drugs',
  'Prophylaxis and chronic treatment of asthma, allergic rhinitis, exercise-induced bronchoconstriction.',
  'Montelukast is a selective leukotriene receptor antagonist that blocks the CysLT1 receptor, inhibiting the effects of cysteinyl leukotrienes.',
  'Blocks CysLT1 receptors in the airways, reducing bronchoconstriction, mucus secretion, and airway inflammation.',
  '10mg once daily in the evening.',
  '4mg (2-5 years), 5mg (6-14 years) chewable tablets once daily in the evening.',
  'Take in the evening for asthma. Can be taken with or without food.',
  'Hypersensitivity to montelukast.',
  'Headache, abdominal pain, thirst. Rare: Neuropsychiatric events (agitation, depression, suicidal thinking).',
  'Not for acute asthma attacks. Monitor for behavioral changes.',
  'Phenobarbital, rifampicin: May reduce montelukast levels.',
  'No specific data. Provide supportive care.',
  'B', 'Excreted in breast milk. Use with caution.',
  'Store below 30°C. Protect from light and moisture.', true
),
-- Pantoprazole 40mg
(
  'Pantonix 40', 'Pantoprazole', 'Tablet', '40mg', 'Opsonin Pharma Limited',
  7.00, 70.00, '10 tablets/strip', 'Proton Pump Inhibitor', 'Anti-Ulcerant Drugs',
  'GERD, peptic ulcer, Zollinger-Ellison syndrome, stress ulcer prophylaxis.',
  'Pantoprazole is a proton pump inhibitor that suppresses the final step in gastric acid production by forming a covalent bond with the H+/K+ ATPase enzyme.',
  'Irreversibly inhibits the gastric proton pump in parietal cells.',
  '40mg once daily for 4-8 weeks.',
  'Not established for children under 5 years.',
  'Take before breakfast. Swallow whole, do not crush.',
  'Hypersensitivity to pantoprazole or substituted benzimidazoles.',
  'Headache, diarrhea, nausea, abdominal pain, flatulence.',
  'Long-term use may cause hypomagnesemia, vitamin B12 deficiency, increased fracture risk.',
  'Atazanavir, nelfinavir: Reduced absorption. Methotrexate: Increased levels.',
  'No specific antidote. Symptomatic treatment.',
  'B', 'Excreted in breast milk. Caution advised.',
  'Store below 25°C. Protect from moisture.', true
)
ON CONFLICT DO NOTHING;