// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjowmwyaribfewhbaazl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqb3dtd3lhcmliZmV3aGJhYXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU2NzcsImV4cCI6MjA4Mzk5MTY3N30.D-F39Tn63HPdHTvYIbe2DQ_Jw9zDJj4C4WlZBqn34-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});